### ISSUE TITLE
Permissions issue when running the plugin on gitlab-ci

### ISSUE THREAD

**Issue by hcabnettek** [bmuschko/gradle-docker-plugin#463]
Locally using gradle this works great. But when I try to use it in CI, I get an * What went wrong:
Execution failed for task ':buildDockerImage'.
> org.newsclub.net.unix.AFUNIXSocketException: Permission denied (socket: /var/run/docker.sock)

.gitlab-ci.yaml
````yaml
image: gradle:alpine

stages:
  - build

gradle-build:
  stage: build
  script: ./gradlew -Puser=gitlab-ci-token -Ppassword=$CI_JOB_TOKEN -Purl=$CI_REGISTRY buildDockerImage
````
the ci runner has docker installed and gitlab-runner was added to group Docker, but it must not be using that user.  Any ideas as to how I can fix this? I was thinking have dockerd use tcp, but I'm not really sure how to set that up. I would like to use the unix sock if possible. Thanks for any help.
