### ISSUE TITLE
SpringBootAppPlugin: Cannot pass environment vars to container 

### ISSUE THREAD

**Issue by thetric** [bmuschko/gradle-docker-plugin#647]
I migrated my Spring Boot app from the DockerJavaAppPlugin + Gradle's `application` plugin to the simpler DockerSpringBootAppPlugin and wondered why I couldn't pass `JAVA_OPTS` to the container:

```yml
# docker-compose.yml
version: '3'
services:
  presence:
    image: thetric/gradle-docker-plugin-java-opts-issue:latest
    environment:
    - >
      JAVA_OPTS=-Dspring.profiles.active=custom-profile
```

### Expected Behavior
It should be possible to pass JVM args to the container (like in the DockerJavaAppPlugin+`application` plugin combo). E.g. the Spring Boot app should pick up the profile specified in the `JAVA_OPTS`:
```
The following profiles are active: custom-profile
```

### Current Behavior
But instead `JAVA_OPTS` is ignored:

```
No active profile set, falling back to default profiles: default
```

### Context
I'm trying to pass JVM args to the Docker container generated by the DockerSpringBootAppPlugin. The image shouldn't contain hardcoded environment vars as it should run in different configs.

### Steps to Reproduce (for bugs)
Repro project: https://github.com/thetric/gradle-docker-spring-boot-app-plugin-bug-repo

```
./gradlew dBI && docker-compose up
```

### Your Environment
Gradle 4.9
JDK 8u161, CentOS 7.3, amd64, Docker 18.06.0.ce
JDK 8u181/JDK 10.0.2 Arch Linux (kernel: 4.17.14), amd64, Docker 18.05.0-ce
