### ISSUE TITLE
Can't add arguments for entrypoint command with Spring Boot Application.

### ISSUE THREAD

**Issue by JamesZBL** [bmuschko/gradle-docker-plugin#793]
I tried to add a default command for entrypoint with Spring Boot Application:
```groovy
    docker {
        registryCredentials {
            url = "${registryHost}"
            username = "${System.env.PRIVATE_REG_USERNAME}"
            password = "${System.env.PRIVATE_REG_PASSWORD}"
        }

        springBootApplication {
            baseImage = 'openjdk:8-jdk-alpine'
            exec {
                defaultCommand '-Dspring.profiles.active=test'
            }
        }
    }
```
But there is not a property named 'exec' in sprintBootApplication.
Please consider about add a support for this.

**Comment by bmuschko** [comment]
The next release of the plugin is going to introduce an option for passing in JVM parameters (see https://github.com/bmuschko/gradle-docker-plugin/pull/790). I am going to release a new version soon to solve your use case.

**Comment by JamesZBL** [comment]
# Solved ! 
When you using docker compose file, you can add `command` into a service like this:
```yaml
services:
  api:
    image: app/api:latest
    command: ["-Dspring.profiles.active=test"]
    : unless-stopped
    networks:
      - app
    ports:
      - "8080:8080"
  # <other services...>
```
